-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.ScalarCodecs exposing (Date, DateTime, GitObjectID, GitSSHRemote, GitTimestamp, Html, Id, PreciseDateTime, Uri, X509Certificate, codecs)

import Api.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Date =
    Api.Scalar.Date


type alias DateTime =
    Api.Scalar.DateTime


type alias GitObjectID =
    Api.Scalar.GitObjectID


type alias GitSSHRemote =
    Api.Scalar.GitSSHRemote


type alias GitTimestamp =
    Api.Scalar.GitTimestamp


type alias Html =
    Api.Scalar.Html


type alias Id =
    Api.Scalar.Id


type alias PreciseDateTime =
    Api.Scalar.PreciseDateTime


type alias Uri =
    Api.Scalar.Uri


type alias X509Certificate =
    Api.Scalar.X509Certificate


codecs : Api.Scalar.Codecs Date DateTime GitObjectID GitSSHRemote GitTimestamp Html Id PreciseDateTime Uri X509Certificate
codecs =
    Api.Scalar.defineCodecs
        { codecDate = defaultCodecs.codecDate
        , codecDateTime = defaultCodecs.codecDateTime
        , codecGitObjectID = defaultCodecs.codecGitObjectID
        , codecGitSSHRemote = defaultCodecs.codecGitSSHRemote
        , codecGitTimestamp = defaultCodecs.codecGitTimestamp
        , codecHtml = defaultCodecs.codecHtml
        , codecId = defaultCodecs.codecId
        , codecPreciseDateTime = defaultCodecs.codecPreciseDateTime
        , codecUri = defaultCodecs.codecUri
        , codecX509Certificate = defaultCodecs.codecX509Certificate
        }
