-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.ContributionCalendarWeek exposing (contributionDays, firstDay)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The days of contributions in this week.
-}
contributionDays : SelectionSet decodesTo Api.Object.ContributionCalendarDay -> SelectionSet (List decodesTo) Api.Object.ContributionCalendarWeek
contributionDays object_ =
    Object.selectionForCompositeField "contributionDays" [] object_ (identity >> Decode.list)


{-| The date of the earliest square in this week.
-}
firstDay : SelectionSet Api.ScalarCodecs.Date Api.Object.ContributionCalendarWeek
firstDay =
    Object.selectionForField "ScalarCodecs.Date" "firstDay" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDate |> .decoder)
