-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Enterprise exposing (AvatarUrlOptionalArguments, MembersOptionalArguments, OrganizationsOptionalArguments, UserAccountsOptionalArguments, avatarUrl, billingInfo, createdAt, databaseId, description, descriptionHTML, id, location, members, name, organizations, ownerInfo, resourcePath, url, userAccounts, viewerIsAdmin, websiteUrl)

import Api.Enum.EnterpriseUserAccountMembershipRole
import Api.Enum.EnterpriseUserDeployment
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


type alias AvatarUrlOptionalArguments =
    { size : OptionalArgument Int }


{-| A URL pointing to the enterprise's public avatar.

  - size - The size of the resulting square image.

-}
avatarUrl : (AvatarUrlOptionalArguments -> AvatarUrlOptionalArguments) -> SelectionSet Api.ScalarCodecs.Uri Api.Object.Enterprise
avatarUrl fillInOptionals =
    let
        filledInOptionals =
            fillInOptionals { size = Absent }

        optionalArgs =
            [ Argument.optional "size" filledInOptionals.size Encode.int ]
                |> List.filterMap identity
    in
    Object.selectionForField "ScalarCodecs.Uri" "avatarUrl" optionalArgs (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecUri |> .decoder)


{-| Enterprise billing information visible to enterprise billing managers.
-}
billingInfo : SelectionSet decodesTo Api.Object.EnterpriseBillingInfo -> SelectionSet (Maybe decodesTo) Api.Object.Enterprise
billingInfo object_ =
    Object.selectionForCompositeField "billingInfo" [] object_ (identity >> Decode.nullable)


{-| Identifies the date and time when the object was created.
-}
createdAt : SelectionSet Api.ScalarCodecs.DateTime Api.Object.Enterprise
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| Identifies the primary key from the database.
-}
databaseId : SelectionSet (Maybe Int) Api.Object.Enterprise
databaseId =
    Object.selectionForField "(Maybe Int)" "databaseId" [] (Decode.int |> Decode.nullable)


{-| The description of the enterprise.
-}
description : SelectionSet (Maybe String) Api.Object.Enterprise
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


{-| The description of the enterprise as HTML.
-}
descriptionHTML : SelectionSet Api.ScalarCodecs.Html Api.Object.Enterprise
descriptionHTML =
    Object.selectionForField "ScalarCodecs.Html" "descriptionHTML" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecHtml |> .decoder)


id : SelectionSet Api.ScalarCodecs.Id Api.Object.Enterprise
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The location of the enterprise.
-}
location : SelectionSet (Maybe String) Api.Object.Enterprise
location =
    Object.selectionForField "(Maybe String)" "location" [] (Decode.string |> Decode.nullable)


type alias MembersOptionalArguments =
    { organizationLogins : OptionalArgument (List String)
    , query : OptionalArgument String
    , orderBy : OptionalArgument Api.InputObject.EnterpriseMemberOrder
    , role : OptionalArgument Api.Enum.EnterpriseUserAccountMembershipRole.EnterpriseUserAccountMembershipRole
    , deployment : OptionalArgument Api.Enum.EnterpriseUserDeployment.EnterpriseUserDeployment
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of users who are members of this enterprise.

  - organizationLogins - Only return members within the organizations with these logins
  - query - The search string to look for.
  - orderBy - Ordering options for members returned from the connection.
  - role - The role of the user in the enterprise organization or server.
  - deployment - Only return members within the selected GitHub Enterprise deployment
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
members : (MembersOptionalArguments -> MembersOptionalArguments) -> SelectionSet decodesTo Api.Object.EnterpriseMemberConnection -> SelectionSet decodesTo Api.Object.Enterprise
members fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { organizationLogins = Absent, query = Absent, orderBy = Absent, role = Absent, deployment = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs =
            [ Argument.optional "organizationLogins" filledInOptionals.organizationLogins (Encode.string |> Encode.list), Argument.optional "query" filledInOptionals.query Encode.string, Argument.optional "orderBy" filledInOptionals.orderBy Api.InputObject.encodeEnterpriseMemberOrder, Argument.optional "role" filledInOptionals.role (Encode.enum Api.Enum.EnterpriseUserAccountMembershipRole.toString), Argument.optional "deployment" filledInOptionals.deployment (Encode.enum Api.Enum.EnterpriseUserDeployment.toString), Argument.optional "after" filledInOptionals.after Encode.string, Argument.optional "before" filledInOptionals.before Encode.string, Argument.optional "first" filledInOptionals.first Encode.int, Argument.optional "last" filledInOptionals.last Encode.int ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "members" optionalArgs object_ identity


{-| The name of the enterprise.
-}
name : SelectionSet String Api.Object.Enterprise
name =
    Object.selectionForField "String" "name" [] Decode.string


type alias OrganizationsOptionalArguments =
    { query : OptionalArgument String
    , orderBy : OptionalArgument Api.InputObject.OrganizationOrder
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of organizations that belong to this enterprise.

  - query - The search string to look for.
  - orderBy - Ordering options for organizations returned from the connection.
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
organizations : (OrganizationsOptionalArguments -> OrganizationsOptionalArguments) -> SelectionSet decodesTo Api.Object.OrganizationConnection -> SelectionSet decodesTo Api.Object.Enterprise
organizations fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { query = Absent, orderBy = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs =
            [ Argument.optional "query" filledInOptionals.query Encode.string, Argument.optional "orderBy" filledInOptionals.orderBy Api.InputObject.encodeOrganizationOrder, Argument.optional "after" filledInOptionals.after Encode.string, Argument.optional "before" filledInOptionals.before Encode.string, Argument.optional "first" filledInOptionals.first Encode.int, Argument.optional "last" filledInOptionals.last Encode.int ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "organizations" optionalArgs object_ identity


{-| Enterprise information only visible to enterprise owners.
-}
ownerInfo : SelectionSet decodesTo Api.Object.EnterpriseOwnerInfo -> SelectionSet (Maybe decodesTo) Api.Object.Enterprise
ownerInfo object_ =
    Object.selectionForCompositeField "ownerInfo" [] object_ (identity >> Decode.nullable)


{-| The HTTP path for this enterprise.
-}
resourcePath : SelectionSet Api.ScalarCodecs.Uri Api.Object.Enterprise
resourcePath =
    Object.selectionForField "ScalarCodecs.Uri" "resourcePath" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecUri |> .decoder)


{-| The HTTP URL for this enterprise.
-}
url : SelectionSet Api.ScalarCodecs.Uri Api.Object.Enterprise
url =
    Object.selectionForField "ScalarCodecs.Uri" "url" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecUri |> .decoder)


type alias UserAccountsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of user accounts on this enterprise.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
userAccounts : (UserAccountsOptionalArguments -> UserAccountsOptionalArguments) -> SelectionSet decodesTo Api.Object.EnterpriseUserAccountConnection -> SelectionSet decodesTo Api.Object.Enterprise
userAccounts fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs =
            [ Argument.optional "after" filledInOptionals.after Encode.string, Argument.optional "before" filledInOptionals.before Encode.string, Argument.optional "first" filledInOptionals.first Encode.int, Argument.optional "last" filledInOptionals.last Encode.int ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "userAccounts" optionalArgs object_ identity


{-| Is the current viewer an admin of this enterprise?
-}
viewerIsAdmin : SelectionSet Bool Api.Object.Enterprise
viewerIsAdmin =
    Object.selectionForField "Bool" "viewerIsAdmin" [] Decode.bool


{-| The URL of the enterprise website.
-}
websiteUrl : SelectionSet (Maybe Api.ScalarCodecs.Uri) Api.Object.Enterprise
websiteUrl =
    Object.selectionForField "(Maybe ScalarCodecs.Uri)" "websiteUrl" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecUri |> .decoder |> Decode.nullable)
