-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.OrganizationMemberEdge exposing (cursor, hasTwoFactorEnabled, node, role)

import Api.Enum.OrganizationMemberRole
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| A cursor for use in pagination.
-}
cursor : SelectionSet String Api.Object.OrganizationMemberEdge
cursor =
    Object.selectionForField "String" "cursor" [] Decode.string


{-| Whether the organization member has two factor enabled or not. Returns null if information is not available to viewer.
-}
hasTwoFactorEnabled : SelectionSet (Maybe Bool) Api.Object.OrganizationMemberEdge
hasTwoFactorEnabled =
    Object.selectionForField "(Maybe Bool)" "hasTwoFactorEnabled" [] (Decode.bool |> Decode.nullable)


{-| The item at the end of the edge.
-}
node : SelectionSet decodesTo Api.Object.User -> SelectionSet (Maybe decodesTo) Api.Object.OrganizationMemberEdge
node object_ =
    Object.selectionForCompositeField "node" [] object_ (identity >> Decode.nullable)


{-| The role this user has in the organization.
-}
role : SelectionSet (Maybe Api.Enum.OrganizationMemberRole.OrganizationMemberRole) Api.Object.OrganizationMemberEdge
role =
    Object.selectionForField "(Maybe Enum.OrganizationMemberRole.OrganizationMemberRole)" "role" [] (Api.Enum.OrganizationMemberRole.decoder |> Decode.nullable)
