-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.PermissionSource exposing (organization, permission, source)

import Api.Enum.DefaultRepositoryPermissionField
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The organization the repository belongs to.
-}
organization : SelectionSet decodesTo Api.Object.Organization -> SelectionSet decodesTo Api.Object.PermissionSource
organization object_ =
    Object.selectionForCompositeField "organization" [] object_ identity


{-| The level of access this source has granted to the user.
-}
permission : SelectionSet Api.Enum.DefaultRepositoryPermissionField.DefaultRepositoryPermissionField Api.Object.PermissionSource
permission =
    Object.selectionForField "Enum.DefaultRepositoryPermissionField.DefaultRepositoryPermissionField" "permission" [] Api.Enum.DefaultRepositoryPermissionField.decoder


{-| The source of this permission.
-}
source : SelectionSet decodesTo Api.Union.PermissionGranter -> SelectionSet decodesTo Api.Object.PermissionSource
source object_ =
    Object.selectionForCompositeField "source" [] object_ identity
