-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.PullRequestChangedFile exposing (additions, deletions, path)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The number of additions to the file.
-}
additions : SelectionSet Int Api.Object.PullRequestChangedFile
additions =
    Object.selectionForField "Int" "additions" [] Decode.int


{-| The number of deletions to the file.
-}
deletions : SelectionSet Int Api.Object.PullRequestChangedFile
deletions =
    Object.selectionForField "Int" "deletions" [] Decode.int


{-| The path of the file.
-}
path : SelectionSet String Api.Object.PullRequestChangedFile
path =
    Object.selectionForField "String" "path" [] Decode.string
