-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.PullRequestCommit exposing (commit, id, pullRequest, resourcePath, url)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The Git commit object
-}
commit : SelectionSet decodesTo Api.Object.Commit -> SelectionSet decodesTo Api.Object.PullRequestCommit
commit object_ =
    Object.selectionForCompositeField "commit" [] object_ identity


id : SelectionSet Api.ScalarCodecs.Id Api.Object.PullRequestCommit
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The pull request this commit belongs to
-}
pullRequest : SelectionSet decodesTo Api.Object.PullRequest -> SelectionSet decodesTo Api.Object.PullRequestCommit
pullRequest object_ =
    Object.selectionForCompositeField "pullRequest" [] object_ identity


{-| The HTTP path for this pull request commit
-}
resourcePath : SelectionSet Api.ScalarCodecs.Uri Api.Object.PullRequestCommit
resourcePath =
    Object.selectionForField "ScalarCodecs.Uri" "resourcePath" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecUri |> .decoder)


{-| The HTTP URL for this pull request commit
-}
url : SelectionSet Api.ScalarCodecs.Uri Api.Object.PullRequestCommit
url =
    Object.selectionForField "ScalarCodecs.Uri" "url" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecUri |> .decoder)
