-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.RegistryPackageFile exposing (guid, id, md5, metadataUrl, name, packageVersion, sha1, sha256, size, updatedAt, url)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| A unique identifier for this file.
-}
guid : SelectionSet (Maybe String) Api.Object.RegistryPackageFile
guid =
    Object.selectionForField "(Maybe String)" "guid" [] (Decode.string |> Decode.nullable)


id : SelectionSet Api.ScalarCodecs.Id Api.Object.RegistryPackageFile
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| Identifies the md5.
-}
md5 : SelectionSet (Maybe String) Api.Object.RegistryPackageFile
md5 =
    Object.selectionForField "(Maybe String)" "md5" [] (Decode.string |> Decode.nullable)


{-| URL to download the asset metadata.
-}
metadataUrl : SelectionSet Api.ScalarCodecs.Uri Api.Object.RegistryPackageFile
metadataUrl =
    Object.selectionForField "ScalarCodecs.Uri" "metadataUrl" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecUri |> .decoder)


{-| Name of the file
-}
name : SelectionSet String Api.Object.RegistryPackageFile
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| The package version this file belongs to.
-}
packageVersion : SelectionSet decodesTo Api.Object.RegistryPackageVersion -> SelectionSet decodesTo Api.Object.RegistryPackageFile
packageVersion object_ =
    Object.selectionForCompositeField "packageVersion" [] object_ identity


{-| Identifies the sha1.
-}
sha1 : SelectionSet (Maybe String) Api.Object.RegistryPackageFile
sha1 =
    Object.selectionForField "(Maybe String)" "sha1" [] (Decode.string |> Decode.nullable)


{-| Identifies the sha256.
-}
sha256 : SelectionSet (Maybe String) Api.Object.RegistryPackageFile
sha256 =
    Object.selectionForField "(Maybe String)" "sha256" [] (Decode.string |> Decode.nullable)


{-| Identifies the size.
-}
size : SelectionSet (Maybe Int) Api.Object.RegistryPackageFile
size =
    Object.selectionForField "(Maybe Int)" "size" [] (Decode.int |> Decode.nullable)


{-| Identifies the date and time when the object was last updated.
-}
updatedAt : SelectionSet Api.ScalarCodecs.DateTime Api.Object.RegistryPackageFile
updatedAt =
    Object.selectionForField "ScalarCodecs.DateTime" "updatedAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| URL to download the asset.
-}
url : SelectionSet Api.ScalarCodecs.Uri Api.Object.RegistryPackageFile
url =
    Object.selectionForField "ScalarCodecs.Uri" "url" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecUri |> .decoder)
