-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.RemoveEnterpriseAdminPayload exposing (admin, clientMutationId, enterprise, message, viewer)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The user who was removed as an administrator.
-}
admin : SelectionSet decodesTo Api.Object.User -> SelectionSet (Maybe decodesTo) Api.Object.RemoveEnterpriseAdminPayload
admin object_ =
    Object.selectionForCompositeField "admin" [] object_ (identity >> Decode.nullable)


{-| A unique identifier for the client performing the mutation.
-}
clientMutationId : SelectionSet (Maybe String) Api.Object.RemoveEnterpriseAdminPayload
clientMutationId =
    Object.selectionForField "(Maybe String)" "clientMutationId" [] (Decode.string |> Decode.nullable)


{-| The updated enterprise.
-}
enterprise : SelectionSet decodesTo Api.Object.Enterprise -> SelectionSet (Maybe decodesTo) Api.Object.RemoveEnterpriseAdminPayload
enterprise object_ =
    Object.selectionForCompositeField "enterprise" [] object_ (identity >> Decode.nullable)


{-| A message confirming the result of removing an administrator.
-}
message : SelectionSet (Maybe String) Api.Object.RemoveEnterpriseAdminPayload
message =
    Object.selectionForField "(Maybe String)" "message" [] (Decode.string |> Decode.nullable)


{-| The viewer performing the mutation.
-}
viewer : SelectionSet decodesTo Api.Object.User -> SelectionSet (Maybe decodesTo) Api.Object.RemoveEnterpriseAdminPayload
viewer object_ =
    Object.selectionForCompositeField "viewer" [] object_ (identity >> Decode.nullable)
