-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.RenamedTitleEvent exposing (actor, createdAt, currentTitle, id, previousTitle, subject)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Identifies the actor who performed the event.
-}
actor : SelectionSet decodesTo Api.Interface.Actor -> SelectionSet (Maybe decodesTo) Api.Object.RenamedTitleEvent
actor object_ =
    Object.selectionForCompositeField "actor" [] object_ (identity >> Decode.nullable)


{-| Identifies the date and time when the object was created.
-}
createdAt : SelectionSet Api.ScalarCodecs.DateTime Api.Object.RenamedTitleEvent
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| Identifies the current title of the issue or pull request.
-}
currentTitle : SelectionSet String Api.Object.RenamedTitleEvent
currentTitle =
    Object.selectionForField "String" "currentTitle" [] Decode.string


id : SelectionSet Api.ScalarCodecs.Id Api.Object.RenamedTitleEvent
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| Identifies the previous title of the issue or pull request.
-}
previousTitle : SelectionSet String Api.Object.RenamedTitleEvent
previousTitle =
    Object.selectionForField "String" "previousTitle" [] Decode.string


{-| Subject that was renamed.
-}
subject : SelectionSet decodesTo Api.Union.RenamedTitleSubject -> SelectionSet decodesTo Api.Object.RenamedTitleEvent
subject object_ =
    Object.selectionForCompositeField "subject" [] object_ identity
