-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.SearchResultItemConnection exposing (codeCount, edges, issueCount, nodes, pageInfo, repositoryCount, userCount, wikiCount)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The number of pieces of code that matched the search query.
-}
codeCount : SelectionSet Int Api.Object.SearchResultItemConnection
codeCount =
    Object.selectionForField "Int" "codeCount" [] Decode.int


{-| A list of edges.
-}
edges : SelectionSet decodesTo Api.Object.SearchResultItemEdge -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.SearchResultItemConnection
edges object_ =
    Object.selectionForCompositeField "edges" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| The number of issues that matched the search query.
-}
issueCount : SelectionSet Int Api.Object.SearchResultItemConnection
issueCount =
    Object.selectionForField "Int" "issueCount" [] Decode.int


{-| A list of nodes.
-}
nodes : SelectionSet decodesTo Api.Union.SearchResultItem -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.SearchResultItemConnection
nodes object_ =
    Object.selectionForCompositeField "nodes" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| Information to aid in pagination.
-}
pageInfo : SelectionSet decodesTo Api.Object.PageInfo -> SelectionSet decodesTo Api.Object.SearchResultItemConnection
pageInfo object_ =
    Object.selectionForCompositeField "pageInfo" [] object_ identity


{-| The number of repositories that matched the search query.
-}
repositoryCount : SelectionSet Int Api.Object.SearchResultItemConnection
repositoryCount =
    Object.selectionForField "Int" "repositoryCount" [] Decode.int


{-| The number of users that matched the search query.
-}
userCount : SelectionSet Int Api.Object.SearchResultItemConnection
userCount =
    Object.selectionForField "Int" "userCount" [] Decode.int


{-| The number of wiki pages that matched the search query.
-}
wikiCount : SelectionSet Int Api.Object.SearchResultItemConnection
wikiCount =
    Object.selectionForField "Int" "wikiCount" [] Decode.int
